POST http://localhost:8000/product/createa
Content-Type: application/json

{
  "newProduct": {
    "productTitle": "Cafeteira Nespresso",
    "productBrand": "Nespresso",
    "productCategory": "CAFETEIRAS",
    "productImage": "cafeteira.png",
    "productDescription": "Lorem ipsium bla bla bla",
    "productStockAmount": 40,
    "productTotalOrders": 130,
    "productPrice": {
      "realPrice": 100,
      "finalPrice": 30,
      "discount": 70,
      "installments": 12,
      "interestRate": 0.25,
      "freight": 120
    },
    "productDetails": [
      {
        "title": "Grãos",
        "description": "Lorem Ipsium bla bla bla"
      },
      {
        "title": "Sementes",
        "description": "Lorem Ipsium bla bla bla"
      },
      {
        "title": "Máquinas",
        "description": "Lorem Ipsium bla bla bla"
      },
      {
        "title": "Detalhe 1",
        "description": "Lorem Ipsium bla bla bla"
      },
      {
        "title": "Detalhe 2",
        "description": "Lorem Ipsium bla bla bla"
      }
    ],
    "productImages": [
      {
        "src": "capsula-de-cafe-espresso-pimpinela-gourmet-tres-01.png",
        "alt": "capsula-de-cafe"
      },
      {
        "src": "batedeira.png",
        "alt": "batedeira"
      },
      {
        "src": "cafeteira.png",
        "alt": "cafeteira"
      }
    ],
    "productRate": {
      "oneStars": 23,
      "twoStars": 11,
      "threeStars": 35,
      "fourStars": 128,
      "fiveStars": 256
    },
    "productComments": [
      {
        "name": "José do Papel",
        "pfp": "1629903043818.jpg",
        "level": 4,
        "title": "Produto da China",
        "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae pariatur quisquam, modi debitis deleniti harum! Sequi doloribus possimus natus consequuntur optio labore dolore? Rem, tempore molestias minus odit voluptates nobis?",
        "rateGiven": 5
      },
      {
        "name": "José do Papel",
        "pfp": "1629903043818.jpg",
        "level": 2,
        "title": "Produto da China",
        "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae pariatur quisquam, modi debitis deleniti harum! Sequi doloribus possimus natus consequuntur optio labore dolore? Rem, tempore molestias minus odit voluptates nobis?",
        "rateGiven": 4
      },
      {
        "name": "José do Papel",
        "pfp": "1629903043818.jpg",
        "level": 12,
        "title": "Produto da China",
        "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae pariatur quisquam, modi debitis deleniti harum! Sequi doloribus possimus natus consequuntur optio labore dolore? Rem, tempore molestias minus odit voluptates nobis?",
        "rateGiven": 3
      },
      {
        "name": "José do Papel",
        "pfp": "1629903043818.jpg",
        "level": 1,
        "title": "Produto da China",
        "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae pariatur quisquam, modi debitis deleniti harum! Sequi doloribus possimus natus consequuntur optio labore dolore? Rem, tempore molestias minus odit voluptates nobis?",
        "rateGiven": 2.5
      },
      {
        "name": "José do Papel",
        "pfp": "1629903043818.jpg",
        "level": 7,
        "title": "Produto da China",
        "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae pariatur quisquam, modi debitis deleniti harum! Sequi doloribus possimus natus consequuntur optio labore dolore? Rem, tempore molestias minus odit voluptates nobis?",
        "rateGiven": 1
      }
    ],
    "productSellerId": 25022006,
    "productEnabled": true
  }
}